-- Create specialty_services table
CREATE TABLE specialty_services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    specialty_id INTEGER NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

-- Create service_requests table
CREATE TABLE service_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pet_id INTEGER NOT NULL,
    specialty_service_id INTEGER NOT NULL,
    owner_id INTEGER NOT NULL,
    request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'PENDING',
    PRIMARY KEY (id),
    FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE,
    FOREIGN KEY (specialty_service_id) REFERENCES specialty_services(id) ON DELETE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX idx_service_requests_pet_id ON service_requests(pet_id);
CREATE INDEX idx_service_requests_specialty_service_id ON service_requests(specialty_service_id);
CREATE INDEX idx_service_requests_request_date ON service_requests(request_date);
CREATE INDEX idx_specialty_services_specialty_id ON specialty_services(specialty_id);

-- Insert sample specialty services data
INSERT INTO specialty_services (name, specialty_id, description) VALUES
('Dental Surgery', 1, 'Surgical procedures for dental issues'),
('Orthopedic Surgery', 2, 'Surgical procedures for bone and joint issues'),
('General Checkup', 1, 'Routine health examination');

-- Insert sample service requests data
-- Assuming we have pets with IDs 1-13 from the existing data
INSERT INTO service_requests (pet_id, specialty_service_id, owner_id, request_date, status) VALUES
(1, 1, 1, CURRENT_TIMESTAMP - INTERVAL '10' DAY, 'COMPLETED'),
(2, 2, 2, CURRENT_TIMESTAMP - INTERVAL '8' DAY, 'COMPLETED'),
(3, 1, 3, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 'COMPLETED'),
(4, 3, 4, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 'PENDING'),
(5, 2, 5, CURRENT_TIMESTAMP - INTERVAL '4' DAY, 'COMPLETED'),
(6, 1, 6, CURRENT_TIMESTAMP - INTERVAL '3' DAY, 'COMPLETED'),
(7, 2, 1, CURRENT_TIMESTAMP - INTERVAL '2' DAY, 'COMPLETED'),
(8, 1, 2, CURRENT_TIMESTAMP - INTERVAL '1' DAY, 'PENDING'),
(9, 2, 3, CURRENT_TIMESTAMP, 'PENDING'),
(10, 3, 4, CURRENT_TIMESTAMP, 'PENDING');
