-- Create service_requests table for tracking specialty service requests per pet
CREATE TABLE service_requests (
    id integer generated by default as identity,
    pet_id INTEGER NOT NULL REFERENCES pets(id),
    specialty_id INTEGER NOT NULL REFERENCES specialties(id),
    request_date DATE NOT NULL,
    description VARCHAR(255),
    status VARCHAR(50) DEFAULT 'PENDING',
    primary key (id)
);

-- Create indexes for performance
CREATE INDEX service_requests_pet_id ON service_requests(pet_id);
CREATE INDEX service_requests_specialty_id ON service_requests(specialty_id);
CREATE INDEX service_requests_date ON service_requests(request_date);
CREATE INDEX service_requests_status ON service_requests(status);
