-- Create specialty_services table
-- Links specific services to specialties (e.g., "Teeth Cleaning" within "Dentistry")
CREATE TABLE specialty_services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    specialty_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_specialty_services_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id)
);

-- Create service_requests table
-- Tracks when pets receive specialty services during visits
CREATE TABLE service_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pet_id INTEGER NOT NULL,
    specialty_service_id INTEGER NOT NULL,
    visit_id INTEGER,
    request_date DATE NOT NULL,
    notes VARCHAR(500),
    PRIMARY KEY (id),
    CONSTRAINT fk_service_requests_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_service_requests_specialty_service FOREIGN KEY (specialty_service_id) REFERENCES specialty_services(id),
    CONSTRAINT fk_service_requests_visit FOREIGN KEY (visit_id) REFERENCES visits(id)
);

-- Create indexes for performance
CREATE INDEX idx_service_requests_pet_id ON service_requests(pet_id);
CREATE INDEX idx_service_requests_specialty_service_id ON service_requests(specialty_service_id);
CREATE INDEX idx_specialty_services_specialty_id ON specialty_services(specialty_id);

-- Insert sample specialty services
-- Note: specialty_id references existing specialties from V100_2
INSERT INTO specialty_services (name, description, specialty_id) VALUES
('Teeth Cleaning', 'Professional dental cleaning and oral hygiene', 1),
('Cavity Filling', 'Dental cavity treatment and filling', 1),
('Root Canal', 'Advanced dental root canal procedure', 1),
('Annual Vaccination', 'Yearly vaccination shots', 2),
('Rabies Vaccination', 'Rabies prevention vaccination', 2),
('Emergency Surgery', 'Urgent surgical procedures', 3),
('Orthopedic Surgery', 'Bone and joint surgical procedures', 3),
('Soft Tissue Surgery', 'Surgery on soft tissues and organs', 3);

-- Insert sample service requests
-- Note: pet_id and visit_id reference existing data from V100_2
INSERT INTO service_requests (pet_id, specialty_service_id, visit_id, request_date, notes) VALUES
-- Leo (cat, id=1) - dental services
(1, 1, 1, '2023-01-01', 'Regular teeth cleaning'),
(1, 2, 1, '2023-01-01', 'Small cavity found and filled'),
-- Basil (hamster, id=2) - vaccination
(2, 4, 2, '2023-01-02', 'Annual checkup and vaccination'),
-- Rosy (dog, id=3) - surgery
(3, 6, 3, '2023-01-03', 'Emergency surgery for injury'),
-- Jewel (dog, id=4) - vaccination
(4, 4, 4, '2023-01-04', 'Annual vaccination'),
(4, 5, 4, '2023-01-04', 'Rabies shot'),
-- Iggy (lizard, id=5) - dental
(5, 1, 5, '2023-01-08', 'Teeth cleaning'),
-- George (snake, id=6) - vaccination
(6, 4, 6, '2023-01-08', 'Annual vaccination'),
-- Samantha (cat, id=7) - dental
(7, 1, 7, '2023-02-04', 'Teeth cleaning'),
-- Max (cat, id=8) - surgery
(8, 7, 8, '2023-02-04', 'Orthopedic surgery for leg'),
-- Lucky (bird, id=9) - vaccination
(9, 4, 9, '2023-02-04', 'Annual vaccination'),
-- Mulligan (dog, id=10) - dental
(10, 1, 10, '2023-02-04', 'Teeth cleaning'),
-- Freddy (bird, id=11) - vaccination
(11, 4, 11, '2023-02-04', 'Annual vaccination'),
-- Lucky (dog, id=12) - surgery
(12, 6, 12, '2023-02-04', 'Emergency surgery'),
-- Sly (cat, id=13) - dental
(13, 1, 13, '2023-02-04', 'Teeth cleaning');
