-- Create specialty_services table
CREATE TABLE specialty_services
(
    id           integer generated by default as identity,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(500),
    specialty_id INTEGER      NOT NULL REFERENCES specialties (id),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id)
);

CREATE INDEX specialty_services_name ON specialty_services (name);
CREATE INDEX specialty_services_specialty_id ON specialty_services (specialty_id);

-- Create service_requests table
CREATE TABLE service_requests
(
    id                   integer generated by default as identity,
    pet_id               INTEGER NOT NULL REFERENCES pets (id),
    specialty_service_id INTEGER NOT NULL REFERENCES specialty_services (id),
    request_date         DATE    NOT NULL,
    status               VARCHAR(50) DEFAULT 'PENDING',
    created_at           TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    primary key (id)
);

CREATE INDEX service_requests_pet_id ON service_requests (pet_id);
CREATE INDEX service_requests_specialty_service_id ON service_requests (specialty_service_id);
CREATE INDEX service_requests_request_date ON service_requests (request_date);

-- Insert sample specialty services
INSERT INTO specialty_services (name, description, specialty_id)
SELECT 'Dental Cleaning', 'Professional dental cleaning and examination', id
FROM specialties
WHERE name = 'dentistry';

INSERT INTO specialty_services (name, description, specialty_id)
SELECT 'Surgery Consultation', 'Pre-surgery consultation and planning', id
FROM specialties
WHERE name = 'surgery';

INSERT INTO specialty_services (name, description, specialty_id)
SELECT 'Radiology Scan', 'X-ray and imaging services', id
FROM specialties
WHERE name = 'radiology';

-- Insert sample service requests for testing
INSERT INTO service_requests (pet_id, specialty_service_id, request_date, status)
SELECT p.id, ss.id, CURRENT_DATE - (random() * 30)::int, 'COMPLETED'
FROM pets p
         CROSS JOIN specialty_services ss
WHERE random() < 0.3
LIMIT 50;
